# Generated by Django 2.2.16 on 2022-07-19 08:15

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
        migrations.RenameModel(
            old_name='Genre',
            new_name='Genres',
        ),
        migrations.RenameModel(
            old_name='Title',
            new_name='Titles',
        ),
    ]
